#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=10

start_service() {
	config_load awg_path_optimizer

	local enabled
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/ucode /usr/share/awg-path-optimizer/main.uc
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger awg_path_optimizer
}

reload_service() {
	stop
	start
}
